[tool.poetry]
name = "python"
version = "0.1.0"
description = ""
authors = ["Matthew Quinn <matthew.i.quinn@accenture.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
